### ISSUE TITLE
dotnet-install.ps1 can hang on ARM64 Windows machines

### ISSUE THREAD

**Issue by MattGal** [dotnet/install-scripts#119]
As noted in https://github.com/dotnet/core-eng/issues/11424, we have a persistent trend of dotnet-install.ps1 hanging at the end of its execution when called in a loop by other PS1 scripts.  This is a bit of an usual case as the same scripts are called thousands of times on the same machine, but likely impacts anyone trying to do this manually with similar % hit-rate (about 0.5%)

**Comment by bozturkMSFT** [comment]
Hey @MattGal,
 Please let us know when this happens again. As you know, we are in maintenance mode now and we are only dealing with the incidents. At this stage, this issue doesn't seem like an incident to us considering the low repro rate and the impact.

**Comment by MattGal** [comment]
@JunTaoLuo  FYI.

**Comment by jkotalik** [comment]
We've been seeing this frequently in the aspnetcore repo, seeing ~1 dotnet install hang per test run, causing the entire run to go red. https://dev.azure.com/dnceng/public/_build/results?buildId=940789&view=ms.vss-test-web.build-test-results-tab&runId=29721562&resultId=122742&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
Console log: 'Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test--net6.0' from job b1a2f65e-0efa-4e68-8bce-c50e9239d49a (windows.10.arm64v8.open) executed on machine DDARM64-128

D:\h\w\BCC60A0C\w\AB3B0923\e>call runtests.cmd Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test.dll 6.0.100-alpha.1.20523.3 6.0.0-alpha.1.21054.6 6.0.0-ci Windows.10.Arm64v8.Open arm64 false 6.0.0-alpha.1.21055.6 00:30:00  
Set path to: "D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64;C:\python3.7.0\lib\site-packages\pywin32_system32;C:\python3.7.0\lib\site-packages\pywin32_system32;C:\python3.7.0\Scripts\;C:\python3.7.0\;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Windows\System32\OpenSSH\;D:\Users\runner\AppData\Local\Microsoft\WindowsApps;D:\h\w\BCC60A0C\p\node\bin"

"InstallDotNet D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64 6.0.100-alpha.1.20523.3 arm64 '' $true '' '' $true"
GET https://dot.net/v1/dotnet-install.ps1
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

VERBOSE: dotnet-install: Get-CLIArchitecture-From-Architecture -Architecture "arm64"
VERBOSE: dotnet-install: Get-Specific-Version-From-Version -AzureFeed "https://dotnetcli.azureedge.net/dotnet" -Channel
 "LTS" -Version "6.0.100-alpha.1.20523.3" -JSonFile ""
VERBOSE: dotnet-install: Get-Download-Link -AzureFeed "https://dotnetcli.azureedge.net/dotnet" -SpecificVersion 
"6.0.100-alpha.1.20523.3" -CLIArchitecture "arm64"
VERBOSE: dotnet-install: Get-Product-Version -AzureFeed "https://dotnetcli.azureedge.net/dotnet" -SpecificVersion 
"6.0.100-alpha.1.20523.3"
VERBOSE: dotnet-install: Checking for existence of 
https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-alpha.1.20523.3/productVersion.txt
VERBOSE: dotnet-install: Constructed primary named payload URL: 
https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-alpha.1.20523.3/dotnet-sdk-6.0.100-alpha.1.20523.3-win-arm64.zip
VERBOSE: dotnet-install: Get-LegacyDownload-Link -AzureFeed "https://dotnetcli.azureedge.net/dotnet" -SpecificVersion 
"6.0.100-alpha.1.20523.3" -CLIArchitecture "arm64"
VERBOSE: dotnet-install: Constructed legacy named payload URL: 
https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-alpha.1.20523.3/dotnet-dev-win-arm64.6.0.100-alpha.1.20523.3.zip
VERBOSE: dotnet-install: Resolve-Installation-Path -InstallDir "D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64"
VERBOSE: dotnet-install: InstallRoot: D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64
VERBOSE: dotnet-install: Is-Dotnet-Package-Installed -InstallRoot "D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64" 
-RelativePathToPackage "sdk" -SpecificVersion "6.0.100-alpha.1.20523.3"
VERBOSE: dotnet-install: Is-Dotnet-Package-Installed: 
DotnetPackagePath=D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64\sdk\6.0.100-alpha.1.20523.3
VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''namespaceName' = 
root\cimv2,'queryExpression' = SELECT * FROM Win32_LogicalDisk WHERE DeviceId='D:','queryDialect' = WQL'.
VERBOSE: Operation 'Query CimInstances' complete.
VERBOSE: dotnet-install: Zip path: D:\h\w\BCC60A0C\t\xux4hx2n.oek
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-alpha.1.20523.3/dotnet-sdk-6.0.100-alpha.1.20523.3-win-arm64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-alpha.1.20523.3/dotnet-sdk-6.0.100-alpha.1.20523.3-win-arm64.zip
VERBOSE: dotnet-install: Extract-Dotnet-Package -ZipPath "D:\h\w\BCC60A0C\t\xux4hx2n.oek" -OutPath 
"D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64"
VERBOSE: dotnet-install: Get-List-Of-Directories-And-Versions-To-Unpack-From-Dotnet-Package -Zip 
"System.IO.Compression.ZipArchive" -OutPath "D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64"
VERBOSE: dotnet-install: Directories to unpack: 
host/fxr/6.0.0-alpha.1.20513.9/;packs/Microsoft.AspNetCore.App.Ref/6.0.0-alpha.1.20513.8/;packs/Microsoft.NETCore.App.H
ost.win-arm64/6.0.0-alpha.1.20513.9/;packs/Microsoft.NETCore.App.Ref/6.0.0-alpha.1.20513.9/;packs/Microsoft.WindowsDesk
top.App.Ref/5.0.0-rc.1.20417.4/;packs/NETStandard.Library.Ref/2.1.0/;sdk/6.0.100-alpha.1.20523.3/;shared/Microsoft.AspN
etCore.App/6.0.0-alpha.1.20513.8/;shared/Microsoft.NETCore.App/6.0.0-alpha.1.20513.9/;shared/Microsoft.WindowsDesktop.A
pp/5.0.0-rc.1.20417.4/;templates/6.0.0-alpha.1.20513.8/
VERBOSE: dotnet-install: Checking installation: version = 6.0.100-alpha.1.20523.3
VERBOSE: dotnet-install: Is-Dotnet-Package-Installed -InstallRoot "D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64" 
-RelativePathToPackage "sdk" -SpecificVersion "6.0.100-alpha.1.20523.3"
VERBOSE: dotnet-install: Is-Dotnet-Package-Installed: 
DotnetPackagePath=D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64\sdk\6.0.100-alpha.1.20523.3
dotnet-install: Adding to current process PATH: "D:\h\w\BCC60A0C\w\AB3B0923\e\sdk10919\arm64\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installation finished
['Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test--net6.0' WORK ITEM LOG TRUNCATED: Command timed out, and was killed]
```

**Comment by JunTaoLuo** [comment]
Just an FYI, I was looking at some of the failures last week and here's a few observations:
1. Typically I see something like https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-6420d141f0334e86b0/Microsoft.Extensions.ObjectPool.Tests--net6.0/console.cc57b9f4.log?sv=2019-07-07&se=2021-01-23T12%3A27%3A54Z&sr=c&sp=rl&sig=lXP7O16jvLsh23oZgCDrGkGD2wojIyX6wWg2bwaNT0Y%3D where the script times out after installing SDK and runtime. There is no consistency with which test scripts hang so I don't think it's a product problem.
2. Sometimes I see the hang after installing the SDK like in https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-5818a113ff954f4d96/Microsoft.AspNetCore.DataProtection.StackExchangeRedis.Tests--net461/console.623877ea.log?sv=2019-07-07&se=2021-01-22T12%3A29%3A07Z&sr=c&sp=rl&sig=Ni11b6pOMgiiPcV36rLFeuqD2QjmkdCTRZ1xQb%2BDNhY%3D. This also seems to isolate the issue to the installation step since it's occurring between the two invocations of InstallDotNet: https://github.com/dotnet/aspnetcore/blob/master/eng/helix/content/runtests.cmd#L29-L34
3. I've also observed a non-silent error which may shed some additional light on the situation https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-f5b9da89efc64618ba/Microsoft.AspNetCore.Http.Tests--net6.0/console.e8335a9f.log?sv=2019-07-07&se=2021-01-24T00%3A31%3A49Z&sr=c&sp=rl&sig=RCjH%2BhjoFBZvwKEeNmlqTt2fzM%2BTqrq61OZocW4DelA%3D. Here a AccessViolationException is thrown during installation.

**Comment by bozturkMSFT** [comment]
I see the line "Installation finished." in many of the reports. That is the last executed line in the powershell script:
https://github.com/dotnet/install-scripts/blob/b732e7b618adcfc68f769355cd907aec7e6cd028/src/dotnet-install.ps1#L886
After that, it is not the code from dotnet-install.ps1 that is executing. Therefore, I don't know what changes we can make to the script to have any effect on this.

The other one (Item 3 in @JunTaoLuo's list) looks very low level and we don't have any unsafe C# code in the powershell script. I am not sure how you could get this from purely managed code without using `unsafe` even if you tried.

From the dotnet-install.ps1 perspective, this doesn't look actionable. Since it only happens on ARM64 machines, an x86 emulation problem @MattGal mentioned in the original issue is a more likely culprit here in my opinion.

**Comment by pranavkm** [comment]
> Since it only happens on ARM64 machines, an x86 emulation problem @MattGal mentioned in the original issue is a more likely culprit here in my opinion.

Is there a team we can follow up to help with this?

**Comment by MattGal** [comment]
> > Since it only happens on ARM64 machines, an x86 emulation problem @MattGal mentioned in the original issue is a more likely culprit here in my opinion.
> 
> Is there a team we can follow up to help with this?

I don't have any direct contacts, but you might be able to reach out to the _cobaltselfhost_ distribution list.  Without a reliable repro, it's difficult to know how they can help, but they may have ideas or known Powershell issues.
