### ISSUE TITLE
Is it safe to use the same methods the script does to attain versions & downloads?

### ISSUE THREAD

**Issue by svengeance** [dotnet/install-scripts#131]
Hey guys,

I have a need to be able to calculate the dotnet version to download for end-users, not CI scenarios. This is achievable on Linux, where with package managers I can calculate my desired download with a set of parameters (SDK/Runtime, Desktop/Runtime/AspNetCore, 2.1/3.1/5.0).

However, for Windows, the primary way of downloading dotnet is through the main website.
**Unfortunately** links are _incalculable_, for example: https://download.visualstudio.microsoft.com/download/pr/deffc9d5-ef77-4697-ac6e-33a58ccdc409/8386e478b5823a765dc1361155360877/windowsdesktop-runtime-5.0.2-win-x64.exe -- the guid and random letters (some hash?) prevent me from calculating the URL.

After rummaging around the `dotnet-install.ps1` scripts, I noticed that I can actually achieve what I want by doing two things:

1: Ping https://dotnetcli.blob.core.windows.net/dotnet/{Product}/{X.Y}/latest.version to get the latest version, where {Product} is either Runtime, aspnetcore, or Sdk.
2: Take the latest version and calculate the following URL: https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/5.0.2/windowsdesktop-runtime-5.0.2-win-x64.exe

However - this method is completely undocumented unless you start reading the source of the bash/powershell scripts.

Is this safe for external consumers to do? 
If it's not safe, _by what other method_ can I calculate the download URL for dotnet?

Apologies if this is the wrong place, and thanks in advance for any assistance!

**Comment by bozturkMSFT** [comment]
Hi @svengeance,
 Thanks for reaching out!

 The method you have found should work today, but there is a very good chance that it won't work in the future (as we are already [working](https://github.com/dotnet/install-scripts/pull/113) to move away from using latest.version files). It also won't work for anything released before .NET Core 2.1 since the URLs for those are different than what you have above. So I don't recommend using this approach.

 Though still not documented, there is a better way of doing this: using releases.json files.
 You can find the one for 5.0 here: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json . Simply replace 5.0 with the version you want: 3.1, 3.0, 2.2, 2.1, 1.1, 1.0.
 This file should be more reliable than manually constructing URLs, but keep in mind that it can still be changed in the future.
 
 I, unfortunately, don't know a better way of getting the URLs of the latest installers.

Please let me know if this helps

**Comment by svengeance** [comment]
Thanks for the response!

I had suspected that that relying on your internals was a bit sketchy; thanks for confirming. 
Doubly thanks for the pointer to the release.json. This does indeed look like fewer moving parts for you guys (and people like me), just a bit logic to parse the right URLs.

This does indeed help, and I don't have any more questions - just a parting wish that at some point external users can have some documented of doing this. Whether it be having a calculable file structure, a manifest file (e.x. releases.json), or anything - it would certainly make me feel more comfortable consuming this data.

Cheers, and thanks again!

**Comment by bozturkMSFT** [comment]
We haven't been able to finalize our work around aka.ms links yet and there are still some parts that may change (as you can see, PR isn't merged yet). Therefore, releases.json is probably a better choice.

I understand your concern and agree that having a documented & reliable way of doing this would be better. @leecow do you know if we have anything planned for this?

I will close this issue now, but feel free to comment further if needed.

**Comment by leecow** [comment]
We have a project underway to provide an API for addressing releases.json which will make the experience much better.

**Comment by svengeance** [comment]
Very exciting! I look forward to seeing it in action.
