### ISSUE TITLE
Install fails with curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 54

### ISSUE THREAD

**Issue by AArnott** [dotnet/install-scripts#139]
I had two builds in a row fail with:

```
dotnet-install: Installation finished successfully. 
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where: 
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights. 
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs. 
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer. 
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 54
```

Both times only failed on the mac agent. 
Should we add retries to the script?

**Comment by danmosemsft** [comment]
@bozturkMSFT

**Comment by bozturkMSFT** [comment]
Retries were added recently and should be in effect since February 5th 10AM PST.
I was hoping to see some positive change regarding mac/curl issues after that. Would you say that the frequency of the errors is the same as before?
Can you turn on verbose logging? That could tell us cases where retries helped.

**Comment by AArnott** [comment]
I don't see the errors too often. And this one came in before your update. I'll update to your latest script and reactivate if the problem recurs. Thank you.
