### ISSUE TITLE
Cache & reuse previously downloaded SDK

### ISSUE THREAD

**Issue by rkeithhill** [dotnet/install-scripts#15]
This is an enhancement request for `install-script.ps1/.sh`.  

Can we get a new parameter to request that this script only download the selected SDK **if** it can't find a find previously downloaded SDK in the temp directory (or wherever it places the SDK archive upon download)?  

I know a lot build machines these days start with a fresh image but that isn't the case for our build machines. There really is no need to re-download a several hundred MB file just to overwrite the very same file.  Seems like this could also save bandwidth on Microsoft's Azure servers.

**Comment by donJoseLuis** [comment]
The need tracked in this issue should be evaluated against other re-engineering requirements. Moving to the re-engineering project.

**Comment by bozturkMSFT** [comment]
Hi,

 The scripts are being put into "maintenance mode". This means that the scripts and their ecosystem (i.e. website and feeds) will continue to be monitored, but no new features will be delivered. We are still committed to maintaining the scripts’ high availability and we will quickly respond to any incidents.

 As part of this effort, we are closing the issues that aren't planned to be delivered. Unfortunately, this issue is one of those that didn't make the cut, and therefore will be closed.
 If you think this is a must-fix issue before maintenance mode begins, please feel free to comment.

 Thanks

**Comment by rubensa** [comment]
Ouch!!  I was looking for this feature to be implemented so you could mount a volume in Docker containers with previously downloaded dotnet bundles :(
