### ISSUE TITLE
NoCiOnlyWarning parameter

### ISSUE THREAD

**Issue by matkoch** [dotnet/install-scripts#172]
## Description

Showing the `Note that the intended use of this script is for Continuous Integration (CI) scenarios ...` warning on CI systems is basically meaningless and phony. I propose introducing a new `NoCIOnlyWarning` parameter, which can be passed to suppress the warning.

## Alternative

Detect the different CI systems automatically by checking environment variables.

**Comment by bozturkMSFT** [comment]
Hi @matkoch,
 Thank you for your suggestion.
 The install scripts are in what we call "maintenance mode". Which means that we are fixing only the high-impact bugs and we only update the scripts when there is a change in the URLs that we use to access SDK installation files.
 This issue is out of the maintenance mode definition, and unfortunately cannot be considered at the moment. I have labeled the issue and it can be filtered in the future if needed.
