### ISSUE TITLE
Use releases-index.json as source for "channels"

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/install-scripts#18]
This file contains a list of latest stable releases: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json.

It would be nice if `dotnet-install.ps1` could use this to automatically interpret `-Channel` into the exact version it should download.

Proposed usage:
```
./dotnet-install.ps1 -Channel 2.1 -Runtime aspnetcore
```

How this might work:
The script could download https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json. `-Channel 2.1` maps to this entry:
```js
{
    "channel-version": "2.1",
	// .... other stuff ...
    "releases.json": "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.1/releases.json"
}
```
Next, fetch https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/2.1/releases.json and read the data from this file to find the appropriate file.

**Comment by donJoseLuis** [comment]
The need tracked in this issue should be a requirement in the re-engineering effort. Moving to the re-engineering project.

**Comment by bozturkMSFT** [comment]
Hi,

 The scripts are being put into "maintenance mode". This means that the scripts and their ecosystem (i.e. website and feeds) will continue to be monitored, but no new features will be delivered. We are still committed to maintaining the scripts’ high availability and we will quickly respond to any incidents.

 As part of this effort, we are closing the issues that aren't planned to be delivered. Unfortunately, this issue is one of those that didn't make the cut, and therefore will be closed.
 If you think this is a must-fix issue before maintenance mode begins, please feel free to comment.

 Thanks
