### ISSUE TITLE
Add an alias for `InstallDir` on `dotnet-install.ps1`

### ISSUE THREAD

**Issue by nkolev92** [dotnet/install-scripts#189]
When the internal switch was added in https://github.com/dotnet/install-scripts/pull/177, it broken the automatic short param inference in the powershell script. 

Can we add the `-i`  alias to the install dir parameter?

Note that sh script already has that, https://github.com/dotnet/install-scripts/blob/49d5da7f7d313aa65d24fe95cc29767faef553fd/src/dotnet-install.sh#L1454. 

NuGet uses the script on CI for all of our builds. Fixing it on this end would help us avoid having to path every single release we service.

**Comment by bekir-ozturk** [comment]
Hi @nkolev92,
 Thanks for the issue. We will get this fixed in the next patch.

 Not sure if I fully understand this: "would help us avoid having to path every single release we service". What is the status of your builds now? Is it difficult to edit your pipeline to use `-InstallDir` instead of `-i`?

**Comment by nkolev92** [comment]
@bekir-ozturk 

Our CI scripts are all versioned with the code, but they all download the `dotnet-install.ps1` script to install the SDK version they need. 

Our builds for the active releases are fine right now, and it's not really difficult to fix them, but rather it's just `one of those things`, that someone has to do. The concern is primarily for all the servicing releases we maintain.

**Comment by nkolev92** [comment]
It's a really low effort task for us, but I figured adding the alias in the scripts is even lower effort than that , as it's fix in 1 place rather than the ~10ish releases we maintain :)

**Comment by bekir-ozturk** [comment]
@nkolev92 Thanks for the details. This helps :)

The thing is, we don't own the website that serves the scripts. Taking scripts from here to the repo behind the website is a manual process. That's why we don't deploy frequently and instead do deployment only when we have enough impactful changes to publish.
If I understand this correctly, you are OK for now until you need to do a servicing release. Is that correct? If so, when will you have the earliest servicing release? I can see if we can get this released before that.

**Comment by nkolev92** [comment]
@bekir-ozturk 

We follow the .NET schedule, so monthly. 

I think it's ok if this is fixed in the next opportunity. No need to deploy just this change.
