### ISSUE TITLE
Add install script option to install dependencies

### ISSUE THREAD

**Issue by wli3** [dotnet/install-scripts#2]
Per @richlander :

Open question ... Should the fine folks working on / using the GitHub Actions Runner use the install script to install .NET dependencies?

https://github.com/actions/runner/blob/master/docs/start/envlinux.md

**Comment by donJoseLuis** [comment]
@bozturkMSFT can you discuss with Kathleen how this feature request fits with our short-term goals?

**Comment by donJoseLuis** [comment]
The need tracked in this issue should is tracked as a lower priority item under the re-engineering effort. Moving to the re-engineering project.

**Comment by bozturkMSFT** [comment]
Hi,

 The scripts are being put into "maintenance mode". This means that the scripts and their ecosystem (i.e. website and feeds) will continue to be monitored, but no new features will be delivered. We are still committed to maintaining the scripts’ high availability and we will quickly respond to any incidents.

 As part of this effort, we are closing the issues that aren't planned to be delivered. Unfortunately, this issue is one of those that didn't make the cut, and therefore will be closed.
 If you think this is a must-fix issue before maintenance mode begins, please feel free to comment.

 Thanks

**Comment by mthalman** [comment]
I've added this feature in the overall plan of work for https://github.com/dotnet/core/issues/5651.  We can revisit funding for this when the time comes.
