### ISSUE TITLE
.NET 6 Preview 7 not yet available

### ISSUE THREAD

**Issue by f2calv** [dotnet/install-scripts#204]
So I appreciate I am fast off the starting blocks here, but still... :)

```
Step 18/29 : RUN dotnet-install.sh -c 6.0 -v latest --install-dir /usr/share/dotnet/
 ---> Running in 915e318ee247
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-preview.6.21355.2/dotnet-sdk-6.0.100-preview.6.21355.2-linux-x64.tar.gz
```

Echoes of https://github.com/dotnet/install-scripts/issues/194 - maybe something can be done to tie in new preview releases automatically?

**Comment by bekir-ozturk** [comment]
Hi @f2calv,
 Thanks for the issue. This should be fixed now. Let me know if it still doesn't work for you.
 We have this in our "release checklist" since the preview 4 incident you shared, but it must have ben missed for preview 7.
 We have it in our radar to automate this, though unfortunately it is unlikely to happen before .NET 7.
