### ISSUE TITLE
dotnet-install.ps1 should be supported on unix

### ISSUE THREAD

**Issue by vors** [dotnet/install-scripts#23]
## Steps to reproduce
Run https://dot.net/v1/dotnet-install.ps1 script on pwsh on linux or macOS

## Expected  behavior
Script should work

## Actual behavior
```
Architecture not supported. If you think this is a bug, please report it at https://github.com/dotnet/cli/issues
At /Users/vors/dev/platyPS/dotnet-install.ps1:139 char:19
+ ...   default { throw "Architecture not supported. If you think this is a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Architecture no...tnet/cli/issues:String) [], RuntimeException
+ FullyQualifiedErrorId : Architecture not supported. If you think this is a bug, please report it at https://github.com/dotnet/cli/issues
 

```

## Environment data
`dotnet --info` output:

n/a

I should admit that use case is pretty narrow, but it could be useful for cross-platform projects that are already utilized PowerShell.

**Comment by donJoseLuis** [comment]
The need tracked in this issue should be a requirement in the re-engineering effort. Moving to the re-engineering project.

**Comment by bozturkMSFT** [comment]
Hi,

 The scripts are being put into "maintenance mode". This means that the scripts and their ecosystem (i.e. website and feeds) will continue to be monitored, but no new features will be delivered. We are still committed to maintaining the scripts’ high availability and we will quickly respond to any incidents.

 As part of this effort, we are closing the issues that aren't planned to be delivered. Unfortunately, this issue is one of those that didn't make the cut, and therefore will be closed.
 If you think this is a must-fix issue before maintenance mode begins, please feel free to comment.

 Thanks
