### ISSUE TITLE
Failed the installation in our builds from today

### ISSUE THREAD

**Issue by heng-liu** [dotnet/install-scripts#246]
All our builds failed the dotnet installation starting from today. I could repro with the following command locally:

`Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile C:\repos\NuGet.Client\cli\dotnet-install.ps1`

`.\cli\dotnet-install.ps1 -Channel 5 -Quality Daily -InstallDir C:\repos\NuGet.Client\cli -Version 5.0.200-servicing.21120.4 -Architecture x64 -NoPath`

The output is:
```
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

Failed to resolve the exact version number.
At C:\repos\NuGet.Client\cli\dotnet-install.ps1:1162 char:5
+     throw "Failed to resolve the exact version number."
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to resol...version number.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to resolve the exact version number.
```
Our builds are good yesterday with the old dotnet-install.ps1. I run the same command on the old dotnet-install.ps1, it runs successfully.
`.\cli\dotnet-install.ps1 -Channel 5 -Quality Daily -InstallDir C:\repos\NuGet.Client\cli -Version 5.0.200-servicing.21120.4 -Architecture x64 -NoPath`

**Comment by bekir-ozturk** [comment]
Hi @heng-liu,
 Thank you very much for the issue.
 Even though we responded to your case internally, I would like to clarify it here as well for anyone else having a similar problem.

 `-Quality` should only be used with `-Channel` option. When you ask a build from a "channel", the exact version to be downloaded is left to the scripts to decide. Depending on what quality you specify, the final exact version to be resolved will differ.
 
If you ask for an exact version using `-Version` parameter, that means you have already picked a quality (whatever the quality of that version is). You can no longer specify another quality using `-Quality`.

Previously, the quality was ignored when a version was specified, but now it results in an error. I agree that the given error doesn't help here. We should better clarify what the problem is so that users will know what to do. 
I have created an issue here to track this work: https://github.com/dotnet/install-scripts/issues/247
