### ISSUE TITLE
Passing `-Runtime windowsdesktop` install ONLY windows desktop but not core runtime

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/install-scripts#266]
Compare:
```
.\dotnet-install.ps1 -Channel 6.0 -Runtime aspnetcore
```
This will download and install both `Microsoft.NETCore.App` and `Microsoft.AspNetCore.App`.

But:
```
.\dotnet-install.ps1 -Channel 6.0 -Runtime windowsdesktop
```
Will only install `Microsoft.WindowsDesktop.App` - so for example one doesn't get `dotnet.exe` at all.
This means I have to run two commands to get the windowsdesktop runtime correctly installed, one for `runtime` and one for `windowsdesktop`.

**Comment by YuliiaKovalova** [comment]
Hi @vitek-karas,

I have found this documentation that explains the necessity to have dotnet.exe file for [Microsoft.AspNetCore.App](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-6.0#:~:text=Microsoft.AspNetCore.App-,is%20installed%20when%20the%20.NET%20Core%203.0%20or%20later%20SDK%20is%20installed.,-The%20shared%20framework).
So archive for Microsoft.AspNetCore.App contains **dotnet.exe** by design.
![image](https://user-images.githubusercontent.com/95473390/161959060-3e372884-97fe-43ef-a96f-d854ddf132e5.png)

@mairaw, probably you could provide more information about why **dotnet.exe** isn't included in `Microsoft.WindowsDesktop.App `package?

**Comment by vitek-karas** [comment]
It's not just the `dotnet.exe`, the `windowsdesktop` option doesn't install runtime. So it's impossible to run any application since there's no `coreclr.dll` and so on...

**Comment by YuliiaKovalova** [comment]
@vitek-karas ,
As you can see` Microsoft.NETCore.App` is completely included in` Microsoft.AspNetCore.App`.
![image](https://user-images.githubusercontent.com/95473390/161964843-0cce6196-d272-40e6-8c05-e08fe6ebd9dd.png)

Let's wait for @mairaw response. I hope she knows what stands behind this decision or can redirect to a proper team for finding an explanation.

**Comment by bekir-ozturk** [comment]
Hi @vitek-karas,
 You are absolutely right, there is some inconsistency with the build archives. 
 Install scripts are just extracting the archive they downloaded. The problem is likely in the installer repo or in the release pipeline where the runtime is not being included when creating the archive for windowsdesktop.
 I remember bringing this up a year ago, but if I'm not mistaken the outcome was "it works, let's keep it the same". Things may have changed since, so maybe it is time we ask the same question again.

--------------
 @KathleenDollard @mmitche When installing the runtimes using the archives, there is an inconsistency between what happens with aspnetcore and with windowsdesktop. Please see the scenarios below:

|archive|includes dotnet runtime?| includes aspnetcore runtime?| includes windowsdesktop runtime?|
|--|--|--|--|
| dotnet | yes | | |
| aspnetcore | yes | yes | |
| windowsdesktop | | | yes |

Installing `windowsdesktop` runtime doesn't install `dotnet` runtime. The user needs to invoke the install scripts again to install `dotnet` runtime separately.

Is this a good time to get this fixed or are we OK with people needing to use 2 commands to be able to use windowsdesktop?

**Comment by YuliiaKovalova** [comment]
Hi @vitek-karas ,

You can track the status of your issue here [https://github.com/dotnet/wpf/issues/6398](https://github.com/dotnet/wpf/issues/6398).
It was redirected to a proper team.
