### ISSUE TITLE
sha256 checksum and gnupg signature for dotnet-install.sh

### ISSUE THREAD

**Issue by sarvasana** [dotnet/install-scripts#276]
Please provide a sha256 checksum and gnupg signature for your install script so that we can verify it is not tampered with.

Docs:
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

Repo:
https://github.com/dotnet/install-scripts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by bekir-ozturk** [comment]
Hi @sarvasana, 
 Thanks for the issue.
 This sounds reasonable at first look, but I'm looking to clarify some of my confusion at the same time. It would be great if you could elaborate a bit on your usage scenario.

 1. If a checksum was available, where would you prefer to have it? On docs website or as a file similar to "https://dot.net/v1/dotnet-install.sh.sha256"?
 1. If you can't trust the file you downloaded from dot.net website, how can you trust the checksum from the same website?
 1. Scripts are mainly aimed to be used in CI/CD scenarios. If you don't plan to download the checksum from somewhere, then the other option would probably be to embed it into your pipeline. This will mean that whenever we update the scripts, your CI will break. How would you work with the checksum to prevent this?

**Comment by YarekTyshchenko** [comment]
A GPG signature or sha1sum on the docs page would be sufficient. Stops users being tricked into downloading the script from a similarly named domain

**Comment by sarvasana** [comment]
> If a checksum was available, where would you prefer to have it?

Website

> If you can't trust the file you downloaded from dot.net website, how can you trust the checksum from the same website?

I would use the checksum to verify my download is the same as what Microsoft uploaded. (verify integrity)
I would use the signature to verify Microsoft signed the script. (verify origin)

> Scripts are mainly aimed to be used in CI/CD scenarios. If you don't plan to download the checksum from somewhere, then the other option would probably be to embed it into your pipeline. This will mean that whenever we update the scripts, your CI will break. How would you work with the checksum to prevent this?

It would be good to release versions of this script so that CI can pin on specific version.

**Comment by MichalPavlik** [comment]
@YarekTyshchenko, @sarvasana We are preparing the docs site update and I would like to ask you to try validate the script using published signature/key.

https://dot.net/v1/dotnet-install.sh - script
https://dot.net/v1/dotnet-install.sig - detached signature
https://dot.net/v1/dotnet-install.asc - key

How do you handle trust and validity of the key?

cc:@baronfel

**Comment by YarekTyshchenko** [comment]
> @YarekTyshchenko, @sarvasana We are preparing the docs site update and I would like to ask you to try validate the script using published signature/key.
> 
> https://dot.net/v1/dotnet-install.sh - script https://dot.net/v1/dotnet-install.sig - detached signature https://dot.net/v1/dotnet-install.asc - key
> 
> How do you handle trust and validity of the key?
> 
> cc:@baronfel

This works well

```bash
~/W/dotnet-install-script❯ gpg --verify dotnet-install.sig dotnet-install.sh
gpg: Signature made Fri 22 Sep 2023 16:15:51 BST
gpg:                using RSA key B9CF1A51FC7D3ACF
gpg: Good signature from "Microsoft DevUXTeamPrague <devuxteamprague@microsoft.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2B93 0AB1 228D 11D5 D7F6  B6AC B9CF 1A51 FC7D 3ACF
```

Here's a recording of how I verify the file has not been tampered with:
[![asciicast](https://asciinema.org/a/619884.svg)](https://asciinema.org/a/619884)

Keep in mind that the public key (`asc`) only needs to be imported once, and by some operation procedure, as it shouldn't update often but only when it expires.

The warning comes from the fact that I don't trust this key in my keychain. That's correct, as I'm only trying to verify that the signature was signed by a valid key, not that I trust the public key to sign anything else on my system.

lastly in CI scripts you can use `$?` exit code of `gpg --verify` to fail on tampered files, However, this is missing a check to make sure that /this/ public key was used to sign the script. Its possible that the signature was created by some other key that you imported into your keychain. To avoid this problem you could either check the fingerprint of the signature matches the fingerprint of the MS dev team key, or import the public key into a separate keychain (instead of the default one), and always use that when verifying. IMO this is the prefered way.

Overall, I'd like to thank you for taking the time to implement this, and this is a massive positive step in a good direction. Let me know if I can help with creating documentation for handling the verification

to @sarvasana:
> The key should be stored on a key server.

The key doesn't have to be published to a key server. I view keyservers as more of a personal convenience. For example, github seems to host my public key at `https://github.com/yarektyshchenko.gpg`

**Comment by sarvasana** [comment]
> Overall, I'd like to thank you for taking the time to implement this, and this is a massive positive step in a good direction. Let me know if I can help with creating documentation for handling the verification

I second that. Thank you for all your efforts.


> The key doesn't have to be published to a key server. I view keyservers as more of a personal convenience. 

I agree. To make it more trustworthy maybe the dev team could consider WKD instead.
This way the key can be hosted on the microsoft domain.

See: https://wiki.gnupg.org/WKD

**Comment by MichalPavlik** [comment]
Thank you guys. I prepared update for docs site and I wanted to know if the warning is an issue. Having a separate keyring or checking a fingerprint is something that we should add on top of what we have as a draft now.
