### ISSUE TITLE
dotnet-install.ps1 - how about supporting the most used and most simple use cases?

### ISSUE THREAD

**Issue by schittli** [dotnet/install-scripts#296]
Good evening

I am very sorry, but unfortunately, it is quite embarrassing how `dotnet-install.ps1` was developed, the command line parameters are a terrible mess (What does a version number in the channel parameter have to do with?) and it feels like it was programmed by an apprentice who first experimented with PowerShell and then released it.
Does Microsoft no longer have senior programmers who know how to develop useful, robust, and cool SW that is a joy to use? Someone like that should have accompanied the development and done a review every now and then.

But perhaps there is an motivation to provide Microsoft customers with a tool that supports the top four use cases if a customer explained what that might look like.

Let's try:

### Use Case #1: List installable / available .Net Frameworks
Need to explain that it is very useful not to have to ask google which framework versions are available, but to be able to ask the install script directly?
For example:
```
.\dotnet-install.ps1 -List Online
```

### Use Case #2: List installed .Net Frameworks
Need to explain that it is very important to know what framework versions are installed? There are very many use cases for this.
For example:
```
.\dotnet-install.ps1 -List Local
```

### Use Case #3: Update all installed .Net Frameworks
So for example:
```
.\dotnet-install.ps1 -Update Check
.\dotnet-install.ps1 -Update Install
```

### Use Case #4: Smart installation of a specific Framework related to typical Application requirements
With .Net, we usually get applications wich defines the required Framework, for example: 
* core, latest release of 4.5 » `dotnet-install.ps1` would install 4.5.2
* windowsdesktop, latest release of 4.7 » `dotnet-install.ps1` would install 4.7.2
So for example:
```
# This will search and install the newest Release of 4.x and therefore install 4.8.3761.0
.\dotnet-install.ps1 -Install -Runtime core -VersionBranch 4

# This will search and install the newest Release of 4.5.x and therefore install 4.5.51090
.\dotnet-install.ps1 -Install -Runtime core -VersionBranch 4.5

# This will search and install the newest Release of 4.7.x and therefore install 4.7.3081.0
.\dotnet-install.ps1 -Install -Runtime windowsdesktop -VersionBranch 4.7
```

Thanks a lot, kind regards,
Thomas

**Comment by baronfel** [comment]
Hello, and thank you for your feedback. While we're not actively interested in changing the install-scripts at this time (because they are mostly intended for CI scenarios), I wanted to hopefully give you alternatives to consider for each of your points and link to other repositories where we're exploring other opportunities for managing the distribution of the .NET SDK and Runtimes.

* Listing available .NET SDKs - 
  * for this one, I would refer to the `release-index.json` that is the source of truth for what versions are available from Microsoft. This JSON file can be easily scraped to identify supported versions, and get direct download links. Here's a short version that lists all in-support channels: `curl -s https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json | jq -r '."releases-index" | map(select(."support-phase" == "active" or ."support-phase" == "preview")) | .[] | ."channel-version"'`. You can pull out more information like the most recent version number in each channel easily as well, and then use the `releases.json` property to discover where to download each OS-specific package from.

* Listing installed .NET SDKs/Runtimes
  * this can be done easily today via the `dotnet --list-sdks` and `dotnet --list-runtimes` commands. We don't feel the need to replicate them here as a result.

* Update all .NET SDKs/Runtimes
  * Generally, if you're using a package-based installation (MSI, homebrew, linux package manager), you already have a mechanism to do this in a single command. It would just be a maintenance hurdle for us to reimplement that here.
  * If you're using a file-based installation (aka ZIP/Tar.gz extracted to a folder), then update is meaningless - file-based installs have no tracking so you should just install the new version.

* Smart installation of missing frameworks/runtimes
 * this one I'm unclear on - this is the behavior of the scripts today if you use the `channel` parameter, which maps explicitly to the `VersionBranch` concept in your examples.  Worth noting though that throughout your examples you mention .NET Framework - we explicitly do not do anything with Framework in these scripts, nor will we.


Now, there definitely is a case for a consolidated user interface for many of these activities. Rather than rely on scripts, the SDK team is working on a plan for a tool/extension to the SDK that would allow for this kind of management in a more 'native' way than using these scripts. That work can be tracked at https://github.com/dotnet/sdk/issues/23356 and https://github.com/dotnet/sdk/issues/14962, and we'll be working with our partner teams in the Runtime and releases areas to grow that over time.
