### ISSUE TITLE
Is the file structure the scripts expect on the server documented?

### ISSUE THREAD

**Issue by ap0llo** [dotnet/install-scripts#302]
Is there any documentation on the directory & file-structure the scripts (both the Powershell and Bash version) expect to find on the server in order to download a SDK or runtime?

The use-case for this would be setting up a behind-the-firewall mirror of the .NET SDK files that can be used with the (almost) same installation scripts (I suppose modifying the base urls might be sufficient)

**Comment by YuliiaKovalova** [comment]
Hi @mairaw,

Do you know if anyone can provide this information?
Thank you!

**Comment by mmitche** [comment]
I don't think this is explicitly documented but it could be derived from the install scripts. Your use case scenario would work, with one caveat that the "latest" install scenarios wouldn't work, since those depend on aka.ms links today. Anyways, the format is as follows:

1. Take the base storage path (this is what is fed in as -AzureFeed. For example: https://dotnetcli.blob.core.windows.net/dotnet.
2. Add the component path element.
  - Core runtimes - `Runtime`
  - Sdks - `Sdk`
  - Aspnetcore runtimes - `aspnetcore`
  - Windows Desktop runtimes - `windowsdesktop`
3. Add the version number. E.g. 6.0.8
4. Add asset name. The asset names contain the version number too. E.g. dotnet-runtime-6.0.8-win-x64.zip

E.g. `https://dotnetcli.blob.core.windows.net/dotnet/Runtime/6.0.8/dotnet-runtime-6.0.8-osx-x64.pkg`

**Comment by ap0llo** [comment]
Thanks for your answer, I'll look into the script for more detail
