### ISSUE TITLE
Fix dotnet-install.ps1 to use TLS 1.2

### ISSUE THREAD

**Issue by Matt2021-A** [dotnet/install-scripts#362]
on windows server 2016 machines the default protocol is not TLS 1.2 - please update. 

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by YuliiaKovalova** [comment]
Hi @Matt2021-A,

We do not plan to introduce this behavior by default due to non-deterministic consequences for other environments.
I can recommend you use [this one-liner](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#:~:text=%2DProxyUseDefaultCredentials%3B-,Obtain%20script%20and%20install%20.NET%20CLI%20one%2Dliner%20examples%3A,-Windows%3A) for running the script with enabled Tls 1.2.
