### ISSUE TITLE
Failing tests in PR Validation pipeline

### ISSUE THREAD

**Issue by f-alizada** [dotnet/install-scripts#493]
## Context
There is PR: https://github.com/dotnet/install-scripts/pull/491 with constanly failing tests. 

## Goal
Since the changes are not related to the failing tests, the goal is to fix it

## Investigation 
The akams link: https://aka.ms/dotnet/6.0.1xx/signed/dotnet-sdk-win-x64.zip 
Leads to: https://dotnetstage.blob.core.windows.net/6-0-411-servicing-23319-4-public/index.json/Sdk/6.0.314-servicing.23319.2/dotnet-sdk-6.0.314-win-x64.zip

The later is not publicly accessible, however it was before, which resulted the test to start failing.

**Comment by f-alizada** [comment]
@MilenaHristova could you please a look if it is expected change?

**Comment by MilenaHristova** [comment]
> @MilenaHristova could you please a look if it is expected change?

@andriipatsula has more context here

**Comment by MilenaHristova** [comment]
We didn't change policies on the storage account or disabled public access so that's not the cause

The url looks wrong - it's containing `index.json` so this is probably coming from the aka.ms links creation stage. We have a known issue https://github.com/dotnet/release/issues/872 so I'll try to find out when was this link created

But the latest build has a different error
```
dotnet-install: Downloading from "aka.ms" link has failed with error:
Uri: https://dotnetstage.blob.core.windows.net/public/aspnetcore/Runtime/6.0.0-preview.2.21154.6/aspnetcore-runtime-6.0.0-preview.2.21154.6-win-x64.zip
StatusCode: 409
```
This is interesting because this file does exist, also 6 preview 2 is a very old build so it's nothing that changed recently. I'm not sure what code 409 would mean in this case

**Comment by f-alizada** [comment]
Thank you for the input @MilenaHristova 
From the failed tests is seems that there were some changes related to the quality "Signed", since the only failed tests are "Signed" quality   and channel  6.0.1-preview2 :
https://dev.azure.com/dnceng-public/public/_build/results?buildId=740437&view=ms.vss-test-web.build-test-results-tab
Maybe there were some changes regarding specificly 6.0.1-preview2 or only signed quality related.

**Comment by MilenaHristova** [comment]
@f-alizada correction: we **did** change the configuration and disabled anonymous access (probably on accident). I enabled it back and was able to download

**Comment by f-alizada** [comment]
Thank you for enabling it :) Tests are green and the PR is merged. 
Closing the issue.
