### ISSUE TITLE
Use global.json from current directory automatically

### ISSUE THREAD

**Issue by daniel-white** [dotnet/install-scripts#5]
It would be great if I could do `dotnet-install.sh` like `nvm use` where the current directory is consulted and installs that specific version specified in global.json. I know theres the `--jsonfile` option, but the file name is required.

**Comment by donJoseLuis** [comment]
Current dotnet-install script priorities are...
1. improving download resiliency
1. improving documentation
1. re-engineering the scripts (this is where this issue would be considered)

**Comment by bozturkMSFT** [comment]
Hi,

 The scripts are being put into "maintenance mode". This means that the scripts and their ecosystem (i.e. website and feeds) will continue to be monitored, but no new features will be delivered. We are still committed to maintaining the scripts’ high availability and we will quickly respond to any incidents.

 As part of this effort, we are closing the issues that aren't planned to be delivered. Unfortunately, this issue is one of those that didn't make the cut, and therefore will be closed.
 If you think this is a must-fix issue before maintenance mode begins, please feel free to comment.

 Thanks
