### ISSUE TITLE
[Infra] Show dotnet-install progress

### ISSUE THREAD

**Issue by riarenas** [dotnet/install-scripts#77]
@Youssef1313 commented on [Thu Aug 27 2020](https://github.com/dotnet/arcade/issues/6057)

On an average internet connection, running Restore.cmd will take a relatively large time to download the required version of the .NET SDK.

```
D:\dotnet\Roslyn>Restore.cmd
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20366.6/dotnet-sdk-5.0.100-preview.7.20366.6-win-x64.zip
```

I think it's a better experience of a progress or something is shown.

- https://stackoverflow.com/questions/21422364/is-there-any-way-to-monitor-the-progress-of-a-download-using-a-webclient-object
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-progress?view=powershell-7

These links might be relevant.

---

@garath commented on [Thu Aug 27 2020](https://github.com/dotnet/arcade/issues/6057#issuecomment-682179703)

@bozturkMSFT This sounds like your team. Where would you like this issue moved to?

---

@dagood commented on [Thu Aug 27 2020](https://github.com/dotnet/arcade/issues/6057#issuecomment-682210049)

The install scripts are over at https://github.com/dotnet/install-scripts now, probably the right place.

---

@bozturkMSFT commented on [Fri Aug 28 2020](https://github.com/dotnet/arcade/issues/6057#issuecomment-682426354)

https://github.com/dotnet/install-scripts is the correct place for install script related issues (I don't have the permission to move it myself). Thanks.

**Comment by bozturkMSFT** [comment]
Hi @riarenas 
 Thank you for moving the issue here. We will estimate and prioritize this once we complete our current roadmap.

**Comment by bozturkMSFT** [comment]
Hi,

 The scripts are being put into "maintenance mode". This means that the scripts and their ecosystem (i.e. website and feeds) will continue to be monitored, but no new features will be delivered. We are still committed to maintaining the scripts’ high availability and we will quickly respond to any incidents.

 As part of this effort, we are closing the issues that aren't planned to be delivered. Unfortunately, this issue is one of those that didn't make the cut, and therefore will be closed.
 If you think this is a must-fix issue before maintenance mode begins, please feel free to comment.

 Thanks
